#Dependecias
FROM node:22-alpine3.23 AS deps
WORKDIR /usr/src/app

COPY package.json ./
COPY yarn.lock ./

RUN yarn install --frozen-lockfile

#   Builder
FROM node:22-alpine3.23 AS builder
WORKDIR /usr/src/app

# copiar de deps los modulos de node
COPY --from=deps /usr/src/app/node_modules ./node_modules

# copiar todo el código fuente de la aplicación 
COPY . .

ARG ORDERS_DATABASE_URL
ENV DATABASE_URL=$ORDERS_DATABASE_URL

RUN yarn prisma generate
# RUN yarn run test
RUN yarn build

RUN yarn install --frozen-lockfile --production && yarn cache clean

#   Crear la imagen de producción
FROM node:22-alpine3.23 AS prod
# Install openssl for runtime
RUN apk add --no-cache openssl
WORKDIR /usr/src/app    

COPY --from=builder /usr/src/app/node_modules ./node_modules
# copiar la carpeta de DIST 
COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/prisma ./prisma
COPY --from=builder /usr/src/app/prisma.config.ts ./ 

USER node

EXPOSE 3000

CMD [ "sh", "-c", "DATABASE_URL=$DATABASE_URL npx prisma migrate deploy && node dist/main.js" ]